[package]
name = "twitch_games"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diacritics = "0.1.3"
rand = "0.8.5"
tokio = { version = "1.25", features = ["full"] }
twitch-irc = "5.0"
